export default {
	// FONT
	FONT_SIZE_SMALL: 14,
	FONT_SIZE_MEDIUM: 16,
	FONT_SIZE_LARGE: 20,

	// FONT FAMILY
	FONG_FAMILY: 'monospace',

	// COLORS
	PRIMARY_COLOR: 'rgb(0, 102, 34)',
	SECONDARY_COLOR: 'rgba(0, 153, 51, 0.2)',
	WHITE_COLOR: '#FFFFFF',
	BLACK_COLOR: '#000000',
	DARK_COLOR: '#000000',
	LIGHT_COLOR: '#FFFFFF',
	// WEIGHT
	FONT_WEIGHT_LIGHT: '400',
	FONT_WEIGHT_MEDIUM: '700',
	FONT_WEIGHT_HEAVY: "bold",

	// IMAGE
	IMAGE_BORDER_RADIUS: 5,
};