export default {
	// FONT
	FONT_SIZE_SMALL: 14,
	FONT_SIZE_MEDIUM: 16,
	FONT_SIZE_LARGE: 20,

	// FONT FAMILY
	FONG_FAMILY: 'monospace',

	// COLORS
	PRIMARY_COLOR: 'rgba(255, 71, 87,1.0)',
	SECONDARY_COLOR: 'rgba(255, 107, 129,1.0)',
	WHITE_COLOR: '#FFFFFF',
	BLACK_COLOR: '#000000',
	DARK_COLOR: '#000000',
	LIGHT_COLOR: '#FFFFFF',
	// WEIGHT
	FONT_WEIGHT_LIGHT: '400',
	FONT_WEIGHT_MEDIUM: '700',
	FONT_WEIGHT_HEAVY: "bold",

	// IMAGE
	IMAGE_BORDER_RADIUS: 5,
};